In [106]:
# imports
import pandas as pd
import seaborn as sns
import statsmodels.formula.api as smf
import statsmodels.api as sm2
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn import metrics 
from sklearn.model_selection  import train_test_split
import numpy as np

# allow plots to appear directly in the notebook
%matplotlib inline

In [107]:
df_macro = pd.read_csv('Macro_Economic.csv', header=0)

In [108]:
df_macro.head()

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
0,1959,1,2710.349,1707.4,286.898,470.045,1886.9,28.98,139.7,2.82,5.8,177.146,0.00,0.00
1,1959,2,2778.801,1733.7,310.859,481.301,1919.7,29.15,141.7,3.08,5.1,177.830,2.34,0.74
2,1959,3,2775.488,1751.8,289.226,491.260,1916.4,29.35,140.5,3.82,5.3,178.657,2.74,1.09
3,1959,4,2785.204,1753.7,299.356,484.052,1931.3,29.37,140.0,4.33,5.6,179.386,0.27,4.06
4,1960,1,2847.699,1770.5,331.722,462.199,1955.5,29.54,139.6,3.50,5.2,180.007,2.31,1.19

In [109]:
df_macro["YearQTR"] = df_macro["year"].astype(str) + '-'+ df_macro["quarter"].astype(str)

In [110]:
df_macro.set_index('YearQTR')

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
YearQTR,,,,,,,,,,,,,,
1959-1,1959,1,2710.349,1707.4,286.898,470.045,1886.9,28.980,139.7,2.82,5.8,177.146,0.00,0.00
1959-2,1959,2,2778.801,1733.7,310.859,481.301,1919.7,29.150,141.7,3.08,5.1,177.830,2.34,0.74
1959-3,1959,3,2775.488,1751.8,289.226,491.260,1916.4,29.350,140.5,3.82,5.3,178.657,2.74,1.09
1959-4,1959,4,2785.204,1753.7,299.356,484.052,1931.3,29.370,140.0,4.33,5.6,179.386,0.27,4.06
1960-1,1960,1,2847.699,1770.5,331.722,462.199,1955.5,29.540,139.6,3.50,5.2,180.007,2.31,1.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2008-3,2008,3,13324.600,9267.7,1990.693,991.551,9838.3,216.889,1474.7,1.17,6.0,305.270,-3.16,4.33
2008-4,2008,4,13141.920,9195.3,1857.661,1007.273,9920.4,212.174,1576.5,0.12,6.9,305.952,-8.79,8.91
2009-1,2009,1,12925.410,9209.2,1558.494,996.287,9926.4,212.671,1592.8,0.22,8.1,306.547,0.94,-0.71
2009-2,2009,2,12901.504,9189.0,1456.678,1023.528,10077.5,214.469,1653.6,0.18,9.2,307.226,3.37,-3.19
2009-3,2009,3,12990.341,9256.0,1486.398,1044.088,10040.6,216.385,1673.9,0.12,9.6,308.013,3.56,-3.44

In [111]:
x_train, x_test, y_train, y_test = train_test_split(df_macro, df_macro['infl'],test_size=0.3, random_state=0)

In [112]:
x_train.set_index('YearQTR')

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
YearQTR,,,,,,,,,,,,,,
1986-1,1986,1,7022.757,4639.3,967.442,728.125,5255.8,108.70,641.0,6.56,7.0,240.094,-4.39,10.95
1989-3,1989,3,7927.393,5236.1,1021.604,791.819,5787.0,125.40,786.6,7.76,5.3,248.067,2.88,4.88
1979-4,1979,4,5889.495,3805.0,786.817,531.126,4284.3,78.00,385.8,11.94,5.9,226.451,14.62,-2.68
1963-4,1963,4,3264.967,2020.6,364.534,532.383,2254.6,30.94,153.7,3.52,5.6,190.668,2.46,1.06
1997-3,1997,3,9932.672,6566.0,1571.426,691.261,7142.4,161.50,1065.5,5.02,4.9,273.852,2.73,2.29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1975-4,1975,4,4977.511,3275.7,530.596,500.141,3736.0,55.80,288.4,5.26,8.3,217.095,6.50,-1.24
2007-1,2007,1,13099.901,9265.1,2132.609,882.766,9830.2,205.92,1379.7,4.95,4.5,300.977,4.58,0.36
1988-2,1988,2,7592.881,5040.8,987.858,765.980,5614.3,118.50,781.4,6.48,5.5,245.021,4.41,2.07
1970-4,1970,4,4256.637,2749.6,458.406,564.666,3135.1,39.90,215.5,4.86,5.8,206.466,5.04,-0.18
2002-1,2002,1,11477.868,7957.3,1789.327,756.915,8611.6,179.30,1185.9,1.75,5.7,287.328,3.59,-1.84

In [113]:
x_test.set_index('YearQTR')

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
YearQTR,,,,,,,,,,,,,,
1963-3,1963,3,3240.332,2003.8,360.102,546.893,2217.9,30.75,152.6,3.38,5.5,190.028,0.78,2.60
1970-2,1970,2,4264.289,2733.2,478.419,576.257,3103.5,38.90,208.0,6.66,4.8,205.052,4.13,2.52
1967-2,1967,2,3919.556,2438.1,440.393,631.430,2750.8,33.40,178.1,3.78,3.8,198.712,3.61,0.17
1968-2,1968,2,4131.998,2563.3,492.026,646.145,2893.5,34.90,190.5,5.50,3.5,200.706,5.77,-0.28
1986-2,1986,2,7050.969,4688.7,945.972,751.334,5315.5,109.50,670.3,6.06,7.2,240.651,2.93,3.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965-1,1965,1,3516.251,2188.8,429.145,508.006,2447.4,31.38,162.0,3.93,4.9,193.709,1.28,2.65
1966-3,1966,3,3853.301,2381.5,470.697,594.514,2657.8,32.85,171.2,5.23,3.8,197.207,4.90,0.33
1988-3,1988,3,7632.082,5080.6,994.204,760.245,5657.5,119.90,783.3,7.22,5.5,245.693,4.70,2.52
1969-1,1969,1,4244.100,2652.9,512.686,633.224,2923.4,36.30,200.7,6.08,3.4,202.161,6.67,-0.58
1973-1,1973,1,4876.166,3167.0,645.654,504.838,3590.7,43.70,252.7,5.98,5.0,211.420,9.26,-3.28

In [114]:
x_train.describe()

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
count,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000,142.000000
mean,1984.169014,2.556338,7286.828817,4873.267606,1025.250338,666.511556,5363.935211,106.334852,675.032394,5.329930,5.902817,240.501190,3.854437,1.455423
std,14.693547,1.133154,3228.228267,2326.989722,585.755810,139.849619,2437.057191,61.397454,455.936754,2.824598,1.439166,37.422852,3.355044,2.787606
min,1959.000000,1.000000,2710.349000,1707.400000,286.246000,470.045000,1886.900000,28.980000,139.700000,0.120000,3.400000,177.146000,-8.790000,-6.790000
25%,1971.250000,2.000000,4466.140250,2907.475000,525.712750,532.125750,3299.375000,41.275000,231.475000,3.502500,5.025000,209.034250,2.285000,0.027500
50%,1984.000000,3.000000,6650.303500,4361.550000,924.569000,666.811000,5054.300000,105.400000,550.350000,4.985000,5.700000,237.222000,3.100000,1.400000
75%,1996.750000,4.000000,9647.790750,6414.175000,1443.992750,771.103000,6993.375000,159.775000,1112.850000,6.945000,6.800000,271.902250,4.847500,2.592500
max,2009.000000,4.000000,13415.266000,9363.600000,2264.721000,1023.528000,10077.500000,218.610000,1653.600000,14.750000,10.700000,307.226000,14.620000,10.950000

In [115]:
x_test.describe()

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
count,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000
mean,1983.196721,2.344262,7068.331213,4713.614754,984.029770,655.919230,5186.245902,102.144852,651.388525,5.269508,5.842623,237.915311,4.210164,1.059672
std,14.770263,1.078351,3205.198123,2296.487905,587.404296,144.091718,2407.113156,61.408602,457.311865,2.775043,1.514096,37.561873,3.014714,2.367783
min,1960.000000,1.000000,2802.616000,1770.500000,259.764000,460.400000,1955.500000,29.540000,139.600000,0.120000,3.400000,180.007000,-0.400000,-5.620000
25%,1970.000000,1.000000,4264.289000,2733.200000,512.686000,520.960000,3103.500000,38.900000,208.000000,3.530000,4.900000,205.052000,2.260000,-0.280000
50%,1983.000000,2.000000,6030.184000,3986.600000,804.242000,644.322000,4572.200000,98.800000,493.200000,5.110000,5.500000,233.781000,3.350000,1.280000
75%,1995.000000,3.000000,9120.684000,6107.600000,1282.090000,773.851000,6666.800000,153.500000,1098.700000,6.270000,6.800000,267.456000,5.490000,2.650000
max,2009.000000,4.000000,13366.865000,9349.600000,2232.193000,1044.088000,10040.600000,216.385000,1673.900000,15.330000,10.400000,308.013000,12.080000,6.360000

In [116]:
df_macro.dtypes

year          int64
quarter       int64
realgdp     float64
realcons    float64
realinv     float64
realgovt    float64
realdpi     float64
cpi         float64
m1          float64
tbilrate    float64
unemp       float64
pop         float64
infl        float64
realint     float64
YearQTR      object
dtype: object

In [117]:
df_macro['column_name'] = pd.to_numeric(df_macro['YearQTR'], errors='coerce')

In [118]:
df_macro.select_dtypes(include=[np.number]).corr(method='pearson')

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint,column_name
year,1.000000,-0.011356,0.984331,0.979991,0.942204,0.861450,0.986156,0.988215,0.973572,-0.174020,0.042711,0.997223,-0.140837,-0.002373,NaN
quarter,-0.011356,1.000000,0.006082,0.005494,0.007072,0.012144,0.005984,0.005042,0.005237,0.011246,-0.004166,0.008334,-0.002453,0.021856,NaN
realgdp,0.984331,0.006082,1.000000,0.999229,0.977708,0.868651,0.999008,0.986524,0.978696,-0.275745,-0.064297,0.993297,-0.191880,-0.048492,NaN
realcons,0.979991,0.005494,0.999229,1.000000,0.976290,0.870713,0.999091,0.983735,0.976946,-0.294004,-0.056163,0.990350,-0.198804,-0.059517,NaN
realinv,0.942204,0.007072,0.977708,0.976290,1.000000,0.794797,0.971564,0.947084,0.933281,-0.273622,-0.185347,0.957720,-0.192416,-0.046433,NaN
realgovt,0.861450,0.012144,0.868651,0.870713,0.794797,1.000000,0.872241,0.882714,0.890436,-0.302875,-0.024619,0.861811,-0.295641,0.049280,NaN
realdpi,0.986156,0.005984,0.999008,0.999091,0.971564,0.872241,1.000000,0.986721,0.977752,-0.270082,-0.030797,0.994238,-0.186683,-0.048834,NaN
cpi,0.988215,0.005042,0.986524,0.983735,0.947084,0.882714,0.986721,1.000000,0.988812,-0.236846,0.024727,0.990182,-0.222361,0.028676,NaN
m1,0.973572,0.005237,0.978696,0.976946,0.933281,0.890436,0.977752,0.988812,1.000000,-0.330426,-0.016397,0.979025,-0.267236,-0.015337,NaN
tbilrate,-0.174020,0.011246,-0.275745,-0.294004,-0.273622,-0.302875,-0.270082,-0.236846,-0.330426,1.000000,0.229969,-0.217566,0.620508,0.298516,NaN
unemp,0.042711,-0.004166,-0.064297,-0.056163,-0.185347,-0.024619,-0.030797,0.024727,-0.016397,0.229969,1.000000,0.008944,0.065015,0.162489,NaN
pop,0.997223,0.008334,0.993297,0.990350,0.957720,0.861811,0.994238,0.990182,0.979025,-0.217566,0.008944,1.000000,-0.163815,-0.020192,NaN
infl,-0.140837,-0.002453,-0.191880,-0.198804,-0.192416,-0.295641,-0.186683,-0.222361,-0.267236,0.620508,0.065015,-0.163815,1.000000,-0.560965,NaN
realint,-0.002373,0.021856,-0.048492,-0.059517,-0.046433,0.049280,-0.048834,0.028676,-0.015337,0.298516,0.162489,-0.020192,-0.560965,1.000000,NaN
column_name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
lm1 = smf.ols(formula="infl ~ tbilrate", data=x_train).fit()
lm1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   infl   R-squared:                       0.366
Model:                            OLS   Adj. R-squared:                  0.362
Method:                 Least Squares   F-statistic:                     80.84
Date:                Thu, 30 Jan 2025   Prob (F-statistic):           1.53e-15
Time:                        16:24:22   Log-Likelihood:                -340.51
No. Observations:                 142   AIC:                             685.0
Df Residuals:                     140   BIC:                             690.9
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0242      0.482      0.050      0.960      -0.928       0.977
tbilrate       0.7186      0.080      8.991      0.000       0.561       0.877
==============================================================================
Omnibus:                       10.038   Durbin-Watson:                   1.840
Prob(Omnibus):                  0.007   Jarque-Bera (JB):               23.479
Skew:                          -0.051   Prob(JB):                     7.97e-06
Kurtosis:                       4.989   Cond. No.                         13.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [120]:
lm1 = smf.ols(formula="infl ~ tbilrate -1", data=x_train).fit()
lm1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                   infl   R-squared (uncentered):                   0.728
Model:                            OLS   Adj. R-squared (uncentered):              0.726
Method:                 Least Squares   F-statistic:                              377.0
Date:                Thu, 30 Jan 2025   Prob (F-statistic):                    1.13e-41
Time:                        16:24:22   Log-Likelihood:                         -340.51
No. Observations:                 142   AIC:                                      683.0
Df Residuals:                     141   BIC:                                      686.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
tbilrate       0.7222      0.037     19.417      0.000       0.649       0.796
==============================================================================
Omnibus:                       10.014   Durbin-Watson:                   1.839
Prob(Omnibus):                  0.007   Jarque-Bera (JB):               23.332
Skew:                          -0.056   Prob(JB):                     8.58e-06
Kurtosis:                       4.983   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [121]:
lm2 = smf.ols(formula="infl ~ tbilrate + realint -1", data=x_train).fit()
lm2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                   infl   R-squared (uncentered):                   0.998
Model:                            OLS   Adj. R-squared (uncentered):              0.998
Method:                 Least Squares   F-statistic:                          3.253e+04
Date:                Thu, 30 Jan 2025   Prob (F-statistic):                   1.71e-187
Time:                        16:24:22   Log-Likelihood:                          3.2867
No. Observations:                 142   AIC:                                     -2.573
Df Residuals:                     140   BIC:                                      3.338
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
tbilrate       0.9978      0.004    255.047      0.000       0.990       1.006
realint       -0.9978      0.008   -132.687      0.000      -1.013      -0.983
==============================================================================
Omnibus:                      308.352   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           113720.592
Skew:                         -11.766   Prob(JB):                         0.00
Kurtosis:                     139.626   Cond. No.                         2.48
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [122]:
lm2_predict=lm2.predict(x_test)

In [123]:
lm2_predict.describe()

count    61.000000
mean      4.200745
std       3.008995
min      -0.398961
25%       2.255163
50%       3.332822
75%       5.478004
max      12.053566
dtype: float64

In [124]:
predict_values=pd.concat([x_test["infl"], x_test['YearQTR'],lm2_predict],axis=1).set_index('YearQTR')
predict_values.columns=["actual_inflation","predicted_inflation"]
predict_values["residual"]=predict_values["actual_inflation"]-predict_values["predicted_inflation"]

In [125]:
predict_values.head()

         actual_inflation  predicted_inflation  residual
YearQTR
1963-3               0.78             0.778462  0.001538
1970-2               4.13             4.131150 -0.001150
1967-2               3.61             3.602159  0.007841
1968-2               5.77             5.767412  0.002588
1986-2               2.93             2.923818  0.006182

In [126]:
mae=metrics.mean_absolute_error(predict_values['actual_inflation'], predict_values['predicted_inflation'])
mse=metrics.mean_squared_error(predict_values['actual_inflation'], predict_values['predicted_inflation'])
rmse=np.sqrt(metrics.mean_squared_error(predict_values['actual_inflation'], predict_values['predicted_inflation']))

In [127]:
print ('mean absolute error', mae)
print ('mean squared error', mse)
print ('root mean squared error', rmse)

mean absolute error 0.009763326342854543
mean squared error 0.00014955392816016135
root mean squared error 0.01222922434826352